---
title: "Plot by second"
output: html_notebook
---

## requirements

```{r, message=FALSE}
library(ggplot2) 
library(plyr)
library(ggseas)
```
### Custom function
```{r}
save.and.print <- function (plot.func, file.name, width = 10, height=20){
  png(file.path("../data", file.name), width, height)
  p <- plot.func()
  print(p)
  dev.off()
  print(plot.func())
}
```
## Load
### From csv
```{r}
exists.rdata.sos.only <- file.exists("../data/sos.only.RData")
if(!exists.rdata.sos.only){
  # read csv
  if(!file.exists("../data/sos.only.csv")){
    stop("File not exist at location to Rmd document: `../data/sos.only.csv`")
  }
  sos.only <- read.csv("../data/sos.only.csv")
  # data format
  sos.only$Created.Date <- as.POSIXct(strptime(sos.only$Created.Date, format = "%m/%d/%Y %I:%M:%S %p")) 
  sos.only$Latitude <- as.double(paste(sos.only$Latitude))
  sos.only$Longitude <- as.double(paste(sos.only$Longitude))
  #
  print("Loaded from csv")
}

```

### From DS

```{r}
if(exists.rdata.sos.only){
  load("../data/sos.only.RData")
  print("Loaded from RData")
}
```

### Aggregate
```{r}
if(!exists.rdata.sos.only){
  sos.only$Month <- as.POSIXct(cut(sos.only$Created.Date,
    breaks = "month"))
  
  sos.only$Week <- as.POSIXct(cut(sos.only$Created.Date,
    breaks = "week",
    start.on.monday = FALSE))
  
  sos.only$Day <- as.POSIXct(cut(sos.only$Created.Date,
    breaks = "day"))
  
  sos.only$Hour <- as.POSIXct(cut(sos.only$Created.Date,
    breaks = "hour"))
  print("Aggregated to diff metircs")
}else{
  print("Skiped Aggregation")
}
```

## Preview
### Head

```{r}
head(sos.only)
```
### Count by period
```{r}
sos.only$n <- 1
Complaint.Type.Count <- ddply(sos.only,c("Complaint.Type"),summarize,Freq=length(n))


Month.Count <- ddply(sos.only,c("Complaint.Type", "Month"),summarize,Freq=length(n))
Week.Count  <- ddply(sos.only,c("Complaint.Type", "Week"),summarize,Freq=length(n))
Day.Count   <- ddply(sos.only,c("Complaint.Type", "Day"),summarize,Freq=length(n))
# Complaint.Type.Count[order(Complaint.Type.Count$Freq),] 
```
### Add Scales
```{r}
# Complaint.Type.Count$Scale <- as.factor( log(c(100000,2,3), base = 108) )
set.scale<- function(level=3){
  level.no <- level
  find.base <- function(DF){
    ceiling( max(DF$Freq)^(1/level.no) )
  }
  find.Scale <- function(DF){
    base <- find.base(DF)
    as.factor( level.no+1-ceiling( log(DF$Freq+1, base=base)) )
  }
  Month.Count$Scale <<- find.Scale(Month.Count)
  Week.Count$Scale <<-find.Scale(Week.Count)
  Day.Count$Scale <<-find.Scale(Day.Count)
}

```


### Plot
```{r}
for(level in 1:6){
  set.scale(level)
  plot.one <- function(){
    p <- ggplot(Week.Count) + 
      geom_point(aes(x=Week, y=Freq, color=Complaint.Type, shape = Complaint.Type), size=1, alpha=1/2)+
      geom_line(aes(x=Week, y=Freq, color=Complaint.Type), size=0.25, alpha=1/2)+
      #scale_linetype_manual(values = c(rep(1, 70), rep(2, 70), rep(3, 70), rep(4, 70), rep(5, 70)))+
      scale_shape_manual(values = rep(1:6,297))+
      scale_x_datetime() + xlab("Week") + ylab("")+
      theme(legend.position="none",)
    if(level > 1){
      p + facet_grid(Scale ~ ., scales = "free_y") 
    }else{
      p
    }
  }
  save.and.print(plot.one, paste0("Week.l", level, ".png"), width = 3500, height=2500)
  #
  plot.one <- function(){
    p <- ggplot(Month.Count) + 
      geom_point(aes(x=Month, y=Freq, color=Complaint.Type, shape = Complaint.Type), size=1, alpha=1/2)+
      geom_line(aes(x=Month, y=Freq, color=Complaint.Type), size=0.25, alpha=1/2)+
      #scale_linetype_manual(values = c(rep(1, 70), rep(2, 70), rep(3, 70), rep(4, 70), rep(5, 70)))+
      scale_shape_manual(values = rep(1:6,297))+
      scale_x_datetime() + xlab("Month") + ylab("")+
      theme(legend.position="none")
    if(level > 1){
      p + facet_grid(Scale ~ ., scales = "free_y") 
    }else{
      p
    }
  }
  save.and.print(plot.one, paste0("Month.l", level, ".png"), width = 3500, height=2500)
  #
  plot.one <- function(){
    p <- ggplot(Day.Count) + 
      geom_point(aes(x=Day, y=Freq, color=Complaint.Type, shape = Complaint.Type), size=1, alpha=1/2)+
      geom_line(aes(x=Day, y=Freq, color=Complaint.Type), size=0.25, alpha=1/2)+
      #scale_linetype_manual(values = c(rep(1, 70), rep(2, 70), rep(3, 70), rep(4, 70), rep(5, 70)))+
      scale_shape_manual(values = rep(1:6,297))+
      scale_x_datetime() + xlab("Day") + ylab("")+
      theme(legend.position="none")
    if(level > 1){
      p + facet_grid(Scale ~ ., scales = "free_y") 
    }else{
      p
    }
  }
  save.and.print(plot.one, paste0("Day.l", level, ".png"), width = 3500, height=2500)
}


```


